FROM ibmcom/websphere-liberty:kernel-java8-openj9-ubi

# Add my app and config
COPY --chown=1001:0  gradle/ /config/gradle/
COPY --chown=1001:0  *gradle* /config/

# Add interim fixes (optional)
#COPY --chown=1001:0  interim-fixes /opt/ibm/fixes/

# Default setting for the verbose option
ARG VERBOSE=false

CMD ls -al
CMD ls -al /gradle/wrapper/


# This script will add the requested XML snippets, grow image to be fit-for-purpose and apply interim fixes
RUN /config/gradlew start open
